<?php

/**
 * PluginsfGuardUserPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserPasswordTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object PluginsfGuardUserPasswordTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginsfGuardUserPassword');
  }

  /**
   * Returns if a user password is expired or not
   *
   * @param string $userId
   * @return boolean
   */
  public function isPassExpired($userId)
  {
    $query = $this->createQuery()->where('user_id = ?',$userId)->orderBy('created_at DESC');
    if (!$result = $query->fetchOne())
      return false;

    $whenToExpire = strtotime($result['created_at']) + (60 * 60 * 24 * sfConfig::get('app_sf_guard_extra_plugin_password_expiration_date',100));

    if (time() >= $whenToExpire)
      return true;
    else
      return false;
  }

}