<?php

/**
 * sfGuardUserPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserPasswordTable extends PluginsfGuardUserPasswordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserPassword');
    }
}