<?php

/**
 * sfGuardLoginAttemptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardLoginAttemptTable extends PluginsfGuardLoginAttemptTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardLoginAttemptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardLoginAttempt');
    }
}