<?php

/**
 * BasesfGuardLoginAttempt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip_address
 * @property string $host_name
 * 
 * @method string              getIpAddress()  Returns the current record's "ip_address" value
 * @method string              getHostName()   Returns the current record's "host_name" value
 * @method sfGuardLoginAttempt setIpAddress()  Sets the current record's "ip_address" value
 * @method sfGuardLoginAttempt setHostName()   Sets the current record's "host_name" value
 * 
 * @package    sfDoctrineGuardExtraPlugin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardLoginAttempt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_login_attempt');
        $this->hasColumn('ip_address', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('host_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}